FROM node:alpine

WORKDIR /app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./apps/worker/package.json ./apps/worker/package.json
COPY ./apps/worker/tsconfig.json ./apps/worker/tsconfig.json

RUN pnpm install

COPY ./apps/worker/src ./apps/worker/src

RUN pnpm run db:generate

CMD ["pnpm", "run", "dev:worker"]
