FROM node:alpine

WORKDIR /app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./apps/web ./apps/web

RUN pnpm install
RUN pnpm run build

EXPOSE 3000

# CMD pnpm run $(if [ "$NODE_ENV" = "production" ]; then echo "web:start"; else echo "dev:web"; fi)
CMD ["pnpm", "run", "dev:web"]
