name: Deploy the Worker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.worker
          push: true
          tags: abhoy21/mindsketch-worker:${{ github.sha }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            #!/bin/bash
            if [ ! -d "mindsketch" ]; then
                echo "Creating mindsketch directory..."
                mkdir mindsketch
            fi

            echo "Changing directory to mindsketch..."
            cd mindsketch

            echo "Pulling latest image from Docker Hub..."
            sudo docker pull abhoy21/mindsketch-worker:${{ github.sha }} || {
            echo "Error: Failed to pull latest image from Docker Hub"
            exit 1
            }

            echo "Stopping existing container if it exists..."
            sudo docker stop worker 2>/dev/null || true

            echo "Removing existing container if it exists..."
            sudo docker rm worker 2>/dev/null || true

            echo "Running docker container..."
            sudo docker run -d --name worker -e NODE_ENV=production -e DATABASE_URL=${{secrets.DATABASE_URL}} -e REDIS_URL=${{secrets.REDIS_URL}} abhoy21/mindsketch-worker:${{ github.sha }} || {
            echo "Error: Failed to run docker container"
            exit 1
            }
