name: Deploy the Worker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.worker
          push: true
          tags: abhoy21/mindsketch-worker:${{ github.sha }}

      - name: Copy worker.sh to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          source: ./worker.sh
          target: ~/

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            chmod +x ~/worker.sh
            ~/worker.sh
