name: Deploy Application

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          cat > .env << EOL
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          REDIS_URL=${{ secrets.NEXT_PUBLIC_WS_URL || 'redis://redis:6379' }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          ACCESS_TOKEN_EXPIRES_IN=${{ secrets.ACCESS_TOKEN_EXPIRES_IN || '1d' }}
          REFRESH_TOKEN_EXPIRES_IN=${{ secrets.REFRESH_TOKEN_EXPIRES_IN || '7d' }}
          NEXT_PUBLIC_HTTP_URL=${{ secrets.NEXT_PUBLIC_HTTP_URL || 'http://localhost:8000' }}
          NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL || 'ws://localhost:8080' }}
          EOL

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: azureuser
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            #!/bin/bash
            if [ ! -d "mindsketch" ]; then
                echo "Creating mindsketch directory..."
                mkdir mindsketch
            fi

            echo "Changing directory to mindsketch..."
            cd mindsketch

            echo "Pulling latest commits from GitHub..."
            git pull origi main

            echo "Copying .env file..."
            cp ../.env .

            echo "Stopping existing containers..."
            docker-compose -f docker-compose.prod.yml down || true

            echo "Starting up with docker-compose..."
            docker-compose --env-file .env -f docker-compose.prod.yml up
